const Constants = {

  OK_CODE: 200,
  BAD_REQUEST_CODE: 400,
  BAD_REQUEST_MSG: 'Bad Request',
  UNAUTHORIZED_CODE: 401,
  UNAUTHORIZED_MSG: 'Unauthorized',
  FORBIDDEN_CODE: 403,
  FORBIDDEN_MSG: 'Forbidden',
  NOT_FOUND_CODE: 404,
  NOT_FOUND_MSG: 'Not Found',
  NOT_ACCEPTABLE: 406,
  SERVER_ERROR_CODE: 500,
  SERVER_ERROR_MSG: 'Internal Server Error',

  DESKTOP_MIN: 992,
  TABLET_MAX: 991,
  TABLET_MIN: 768,
  MOBILE_MAX: 767,
};

export default Constants;
